name: Build book

on:
  push:
    branches:
      - main # Adjust this to your default branch
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup environment
        run: |
          pip install uv
          uv pip install --system jupyter-book jupytext beautifulsoup4

      - name: Cache jupyter-cache folder
        uses: actions/cache@v2
        env:
          cache-name: jupyter-cache
        with:
          path: jupyter-book/_build/.jupyter_cache
          key: v1-${{ github.ref }}-${{ hashFiles('notebook_scripts/**/*.py') }}
          restore-keys: |
            v1-${{ github.ref }}-${{ hashFiles('notebook_scripts/**/*.py') }}
            v1-${{ github.ref }}
            v1-refs/heads/master

      - name: Build the JupyterBook
        run: make

  pdfhtml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade uv
          uv pip install --system jupyter-book jupytext beautifulsoup4

      - name: Install Headless Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -yq $(cat .github/workflows/pyppeteer_requirements.txt)

      - name: Install Chromium
        run: uv pip install --system pyppeteer

      - name: Build PDF from HTML (Docs)
        run: make pdf

      - uses: actions/upload-artifact@v4
        with:
          name: PDF_HTML
          path: jupyter-book/_build/pdf/book.pdf

  deploy-preview:
    runs-on: ubuntu-latest
    needs: build-book # Ensure this job runs after build-book
    if: github.event_name == 'pull_request' && github.event.action != 'closed' # Only run for PRs (not closed)
    steps:
      - name: Download HTML artifacts
        uses: actions/download-artifact@v4
        with:
          name: html-artifacts
          path: jupyter-book/_build/html

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./jupyter-book/_build/html
