name: Deploy PR previews

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  build-book:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup environment
        run: |
          pip install uv
          uv pip install --system jupyter-book jupytext beautifulsoup4

      - name: Cache jupyter-cache folder
        uses: actions/cache@v2
        env:
          cache-name: jupyter-cache
        with:
          path: jupyter-book/_build/.jupyter_cache
          key: v1-${{ github.ref }}-${{ hashFiles('notebook_scripts/**/*.py') }}
          restore-keys: |
            v1-${{ github.ref }}-${{ hashFiles('notebook_scripts/**/*.py') }}
            v1-${{ github.ref }}
            v1-refs/heads/master

      - name: Build the JupyterBook
        if: github.event.action != 'closed' # Skip build if PR is closed
        run: make

      - name: Deploy PR preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./jupyter-book/_build/html
